# Generated by Django 5.0.9 on 2024-12-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_accuracy_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='allPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=10)),
                ('predict_date', models.DateField()),
                ('end_date', models.DateField()),
                ('change', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
