# Generated by Django 5.0.9 on 2025-01-02 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_allpredictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accuracy',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=25),
        ),
        migrations.CreateModel(
            name='allPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('predict_date', models.DateField()),
                ('end_date', models.DateField()),
                ('change', models.DecimalField(decimal_places=3, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='allpredictions',
            constraint=models.UniqueConstraint(fields=('user', 'ticker', 'end_date'), name='unique_prediction'),
        ),
    ]
