# Generated by Django 5.0.9 on 2025-01-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_change_allpredictions_end_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('exchange', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='allpredictions',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stocks'),
        ),
    ]
