# Generated by Django 5.0.9 on 2025-01-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_stocks_alter_allpredictions_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpredictions',
            name='counted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='completed_predictions',
            field=models.IntegerField(default=0),
        ),
    ]
